### ISSUE TITLE
Unnecessary project bloat

### ISSUE THREAD

**Issue by dreedyman** [marcodlk/mstc-cloud-tools#3]
The original intent of this project was to break out the client capability from the mstc-astros project for the following reasons:

1. Make the client easily available, 
2. Not have to tightly couple projects (from a dependency management point of view)
3. Reduce the inclusion of unwanted transitive dependencies that a project requires

The inclusion of the `Provider` class brings along unnecessary dependencies:

* flask
* flask-api
* itsdangerous
* werkzeug

The project should remove the `Provider` class and service-side work and focus on the client capabilities.

**Comment by marcodlk** [comment]
That is where I started. However, in order for the client to be generalizable it seems to me that there needs to be some kind of contract between the server and client to establish the rules/formatting the inputs and outputs will follow.  This allows us to encapsulate the process of converting urls to local files on both ends (what is currently ClientProxy and ServerProxy). Otherwise, how do we decouple the data service interactions and handling of input/output urls from the rest of the provider and/or client logic? Should that not be decoupled?

As I note in the README, the BaseProvider, ClientProxy, and ServerProxy in current state are meant to serve more as a “what if” than “let’s use this”. You are right about the original goal though, provide just the minimum required for the client — and BaseProvider reintroduces the dependency bloating we wanted to avoid. I will create the slimmed down branch when I return Monday.

**Comment by marcodlk** [comment]
Created a separate branch with provider, removed unnecessary bloat in master which now only includes Client related code.
